# https://aka.ms/yaml

jobs:

- job: Windows
  pool:
    vmImage: 'win1803'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run test
    displayName: 'npm install and test'